[options]
HoldPkg = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[keskos-local]
SigLevel = Optional TrustAll
Server = __KESKOS_LOCAL_REPO_URI__

[keskos]
# TODO: switch this to `SigLevel = Required DatabaseOptional` once
# `keskos-keyring` is published and the repo server signs packages + metadata.
SigLevel = Optional TrustAll
Server = https://downloads.keskos.org/repo/$repo/os/$arch

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
