#!/usr/bin/env bash

KESK_KCM_BEGIN_MARKER="# BEGIN KESKOS MANAGED KCM RESTRICTIONS"
KESK_KCM_END_MARKER="# END KESKOS MANAGED KCM RESTRICTIONS"
KESK_KCM_GROUP_HEADER='[KDE Control Module Restrictions][$i]'

kesk_kcm_timestamp() {
  date +"%Y-%m-%d %H:%M:%S"
}

kesk_kcm_trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s\n' "$value"
}

kesk_kcm_source_root() {
  local script_dir=""
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cd "${script_dir}/../../../.." && pwd
}

kesk_kcm_resolve_paths() {
  local source_root=""

  source_root="$(kesk_kcm_source_root)"
  KESK_KCM_ROOT="${KESK_KCM_ROOT:-}"
  KESK_KCM_MODE="${KESK_KCM_MODE:-system}"
  KESK_KCM_HOME="${KESK_KCM_HOME:-${HOME}}"
  KESK_KCM_SETTINGS_DIR="${KESK_KCM_SETTINGS_DIR:-${KESK_KCM_ROOT}/usr/share/kesk/settings}"
  KESK_KCM_PRIMARY_CONF="${KESK_KCM_PRIMARY_CONF:-${KESK_KCM_SETTINGS_DIR}/hidden-kcms.conf}"
  KESK_KCM_EXTRA_CONF="${KESK_KCM_EXTRA_CONF:-${KESK_KCM_SETTINGS_DIR}/hidden-kcms-extra.conf}"
  KESK_KCM_DEFAULT_LIST="${KESK_KCM_DEFAULT_LIST:-${KESK_KCM_SETTINGS_DIR}/kcm-default-list.txt}"

  if [[ "${KESK_KCM_MODE}" == "user" ]]; then
    KESK_KCM_KDEGLOBALS="${KESK_KCM_KDEGLOBALS:-${KESK_KCM_HOME}/.config/kdeglobals}"
    KESK_KCM_BACKUP_DIR="${KESK_KCM_BACKUP_DIR:-${KESK_KCM_HOME}/.local/state/kesk/kcm-metadata-backups}"
    KESK_KCM_LOG_FILE="${KESK_KCM_LOG_FILE:-${KESK_KCM_HOME}/.local/state/kesk/logs/kcm-hide.log}"
    KESK_KCM_USER_LIST_OUTPUT="${KESK_KCM_USER_LIST_OUTPUT:-${KESK_KCM_HOME}/.local/state/kesk/kcm-list.txt}"
  else
    KESK_KCM_KDEGLOBALS="${KESK_KCM_KDEGLOBALS:-${KESK_KCM_ROOT}/etc/xdg/kdeglobals}"
    KESK_KCM_BACKUP_DIR="${KESK_KCM_BACKUP_DIR:-${KESK_KCM_ROOT}/var/lib/kesk/kcm-metadata-backups}"
    KESK_KCM_LOG_FILE="${KESK_KCM_LOG_FILE:-${KESK_KCM_ROOT}/var/log/kesk/kcm-hide.log}"
    KESK_KCM_USER_LIST_OUTPUT="${KESK_KCM_USER_LIST_OUTPUT:-${KESK_KCM_HOME}/.local/state/kesk/kcm-list.txt}"
  fi

  KESK_KCM_ABSENT_MARKER="${KESK_KCM_BACKUP_DIR}/kdeglobals.was-absent"
  KESK_KCM_BACKUP_FILE="${KESK_KCM_BACKUP_DIR}/kdeglobals.before-kcm-hide"
  KESK_KCM_QUIET="${KESK_KCM_QUIET:-0}"
  KESK_KCM_INCLUDE_EXTRA="${KESK_KCM_INCLUDE_EXTRA:-0}"
  KESK_KCM_SOURCE_ROOT="$source_root"
}

kesk_kcm_ensure_dirs() {
  mkdir -p "$(dirname "${KESK_KCM_KDEGLOBALS}")"
  mkdir -p "$(dirname "${KESK_KCM_LOG_FILE}")"
  mkdir -p "${KESK_KCM_BACKUP_DIR}"
  mkdir -p "$(dirname "${KESK_KCM_USER_LIST_OUTPUT}")"
}

kesk_kcm_log() {
  local message="$1"

  kesk_kcm_ensure_dirs
  printf '[%s] %s\n' "$(kesk_kcm_timestamp)" "$message" >>"${KESK_KCM_LOG_FILE}"
  if [[ "${KESK_KCM_QUIET}" -ne 1 ]]; then
    printf '[kesk-kcms] %s\n' "$message"
  fi
}

kesk_kcm_backup_target() {
  if [[ -f "${KESK_KCM_KDEGLOBALS}" ]]; then
    if [[ ! -e "${KESK_KCM_BACKUP_FILE}" ]]; then
      cp -a "${KESK_KCM_KDEGLOBALS}" "${KESK_KCM_BACKUP_FILE}"
      kesk_kcm_log "Backed up ${KESK_KCM_KDEGLOBALS} to ${KESK_KCM_BACKUP_FILE}"
    fi
    rm -f "${KESK_KCM_ABSENT_MARKER}"
  elif [[ ! -e "${KESK_KCM_ABSENT_MARKER}" ]]; then
    : >"${KESK_KCM_ABSENT_MARKER}"
    kesk_kcm_log "Recorded that ${KESK_KCM_KDEGLOBALS} did not exist before restrictions were applied"
  fi
}

kesk_kcm_parse_ids() {
  local include_extra="${1:-0}"
  local file_path=""
  local line=""
  local trimmed=""
  local id=""

  declare -gA KESK_KCM_SEEN=()
  declare -ga KESK_KCM_IDS=()

  for file_path in "${KESK_KCM_PRIMARY_CONF}" "${KESK_KCM_EXTRA_CONF}"; do
    if [[ "${file_path}" == "${KESK_KCM_EXTRA_CONF}" && "${include_extra}" -ne 1 ]]; then
      continue
    fi
    [[ -f "${file_path}" ]] || continue

    while IFS= read -r line || [[ -n "$line" ]]; do
      line="${line%%#*}"
      trimmed="$(kesk_kcm_trim "$line")"
      [[ -n "${trimmed}" ]] || continue
      id="${trimmed%%[[:space:]]*}"
      [[ -n "${id}" ]] || continue
      if [[ -z "${KESK_KCM_SEEN[$id]:-}" ]]; then
        KESK_KCM_SEEN["$id"]=1
        KESK_KCM_IDS+=("$id")
      fi
    done <"${file_path}"
  done
}

kesk_kcm_render_block() {
  local output_path="$1"
  local id=""

  {
    printf '%s\n' "${KESK_KCM_BEGIN_MARKER}"
    printf '# Generated by kesk-hide-kcms on %s\n' "$(kesk_kcm_timestamp)"
    printf '%s\n' "${KESK_KCM_GROUP_HEADER}"
    for id in "${KESK_KCM_IDS[@]}"; do
      printf '%s=false\n' "$id"
    done
    printf '%s\n' "${KESK_KCM_END_MARKER}"
  } >"${output_path}"
}

kesk_kcm_strip_block() {
  local source_path="$1"
  local output_path="$2"

  if [[ ! -f "${source_path}" ]]; then
    : >"${output_path}"
    return 0
  fi

  awk -v begin="${KESK_KCM_BEGIN_MARKER}" -v end="${KESK_KCM_END_MARKER}" '
    $0 == begin {
      skip = 1
      next
    }
    $0 == end {
      skip = 0
      next
    }
    skip {
      next
    }
    {
      print
    }
  ' "${source_path}" | awk '
    {
      lines[NR] = $0
    }
    END {
      last = NR
      while (last > 0 && lines[last] ~ /^[[:space:]]*$/) {
        last--
      }
      for (i = 1; i <= last; i++) {
        print lines[i]
      }
    }
  ' >"${output_path}"
}

kesk_kcm_has_block() {
  local source_path="$1"
  [[ -f "${source_path}" ]] || return 1
  grep -Fqx "${KESK_KCM_BEGIN_MARKER}" "${source_path}"
}

kesk_kcm_apply_block() {
  local base_file=""
  local block_file=""
  local merged_file=""
  local base_has_content=0

  kesk_kcm_ensure_dirs
  kesk_kcm_backup_target

  base_file="$(mktemp)"
  block_file="$(mktemp)"
  merged_file="$(mktemp)"

  kesk_kcm_strip_block "${KESK_KCM_KDEGLOBALS}" "${base_file}"
  kesk_kcm_render_block "${block_file}"

  if grep -q '[^[:space:]]' "${base_file}"; then
    base_has_content=1
  fi

  if [[ "${base_has_content}" -eq 1 ]]; then
    cat "${base_file}" >"${merged_file}"
    printf '\n' >>"${merged_file}"
  fi
  cat "${block_file}" >>"${merged_file}"
  printf '\n' >>"${merged_file}"

  if [[ -f "${KESK_KCM_KDEGLOBALS}" ]] && cmp -s "${merged_file}" "${KESK_KCM_KDEGLOBALS}"; then
    rm -f "${base_file}" "${block_file}" "${merged_file}"
    kesk_kcm_log "No KCM visibility changes were needed in ${KESK_KCM_KDEGLOBALS}"
    return 0
  fi

  install -Dm644 "${merged_file}" "${KESK_KCM_KDEGLOBALS}"
  rm -f "${base_file}" "${block_file}" "${merged_file}"
  kesk_kcm_log "Applied ${#KESK_KCM_IDS[@]} KeskOS KCM restriction(s) to ${KESK_KCM_KDEGLOBALS}"
}

kesk_kcm_restore_block() {
  local stripped_file=""

  if [[ ! -f "${KESK_KCM_KDEGLOBALS}" ]]; then
    kesk_kcm_log "Nothing to restore; ${KESK_KCM_KDEGLOBALS} does not exist"
    return 0
  fi

  if ! kesk_kcm_has_block "${KESK_KCM_KDEGLOBALS}"; then
    kesk_kcm_log "Nothing to restore; no KeskOS-managed KCM restriction block was found in ${KESK_KCM_KDEGLOBALS}"
    return 0
  fi

  stripped_file="$(mktemp)"
  kesk_kcm_strip_block "${KESK_KCM_KDEGLOBALS}" "${stripped_file}"

  if grep -q '[^[:space:]]' "${stripped_file}"; then
    install -Dm644 "${stripped_file}" "${KESK_KCM_KDEGLOBALS}"
    kesk_kcm_log "Removed the KeskOS-managed KCM restriction block from ${KESK_KCM_KDEGLOBALS}"
  else
    rm -f "${KESK_KCM_KDEGLOBALS}"
    kesk_kcm_log "Removed ${KESK_KCM_KDEGLOBALS} because it only contained the KeskOS-managed KCM restriction block"
  fi

  rm -f "${stripped_file}"
}

kesk_kcm_read_managed_ids() {
  local source_path="$1"
  local line=""
  local trimmed=""
  local in_block=0

  declare -ga KESK_KCM_MANAGED_IDS=()

  [[ -f "${source_path}" ]] || return 0

  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "${line}" == "${KESK_KCM_BEGIN_MARKER}" ]]; then
      in_block=1
      continue
    fi
    if [[ "${line}" == "${KESK_KCM_END_MARKER}" ]]; then
      in_block=0
      continue
    fi
    [[ "${in_block}" -eq 1 ]] || continue
    [[ "${line}" == "${KESK_KCM_GROUP_HEADER}" ]] && continue
    [[ "${line}" == \#* ]] && continue
    trimmed="$(kesk_kcm_trim "${line%%=*}")"
    [[ -n "${trimmed}" ]] || continue
    KESK_KCM_MANAGED_IDS+=("${trimmed}")
  done <"${source_path}"
}

kesk_kcm_available_list_bin() {
  if command -v kcmshell6 >/dev/null 2>&1; then
    printf 'kcmshell6\n'
    return 0
  fi
  if command -v kcmshell5 >/dev/null 2>&1; then
    printf 'kcmshell5\n'
    return 0
  fi
  return 1
}

kesk_kcm_write_reference_list() {
  local list_bin=""

  list_bin="$(kesk_kcm_available_list_bin || true)"
  [[ -n "${list_bin}" ]] || return 1

  mkdir -p "$(dirname "${KESK_KCM_DEFAULT_LIST}")"
  "${list_bin}" --list >"${KESK_KCM_DEFAULT_LIST}" 2>/dev/null
}
